# Site settings
title: bedeute
email: bedeute@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Website resmi Nanang Budi Utomo alias bedeute, poh, chan, dan terserah kalian mau manggil apa
baseurl: "" # the subpath of your site, e.g. /blog/
url: "bedeute.com" # the base hostname & protocol for your site
twitter_username: bedeute
github_username:  bedeute

# Build settings
markdown: kramdown
