# Site settings
title: Wakuwakuw Mobile | Slicing dev
email: bedeute@gmail.com
description: "Wakuwakuw is Next generation community platform"
keywords: "Wakuwakuw, Next generation community platform, Event and Meetup Organizer"
baseurl: "/wakuwakuw/mobile"
url: "http://mataharilabs.github.io"
twitter_username: bedeute
github_username:  bedeute

# Build settings
markdown: kramdown
permalink: pretty
